default: &default
  adapter: postgresql

development:
  <<: *default
  database: tweet-a-task_development

test:
  <<: *default
  database: tweet-a-task_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>