default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  adapter: postgresql
  database: tweet-a-task_production
  password: <%= ENV['TWEET-A-TASK_DATABASE_PASSWORD'] %>