default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: tweet-a-task_development

test:
  <<: *default
  database: tweet-a-task_test

production:
  <<: *default
  database: tweet-a-task_production
  password: <%= ENV['TWEET-A-TASK_DATABASE_PASSWORD'] %>